Check TPM version
QubesOS/qubes-antievilmaid pull request #45
Opened 2023-05-30 12:53 UTC by SergiiDmytruk

Part of #42 which stands on its own.

Exits with an error if TPM2 is detected.

2023-05-31 08:28 UTC, macpijan commented
@marmarek Shall we work directly in this repo?

As there will be a couple of PRs which do not provide full functionality (to ease the review process with smaller portions of code), shall we create some integration branch, rather than pushing to main? Could you do that? Or perhaps, add some of us as contributors to this repo?

2023-05-31 11:42 UTC, marmarek commented
I'm okay with intermediate changes not having value on their own, as long as they don't break existing functionality. But if some intermediate state won't have neither old nor new version working, I'd prefer you keep that in some separate repo or branch. I don't think github permissions allows giving access to just one branch, so that would better be another repo if that's needed.

2023-05-31 11:48 UTC, miczyg1 requested changes

2023-05-31 11:48 UTC, miczyg1 commented on sbin/anti-evil-maid-lib
> +        message "Failed to determine version of $SYSFS_TPM_DIR"
```suggestion
        message "Failed to determine the version of the TPM"
```

2023-05-31 11:48 UTC, miczyg1 commented on sbin/anti-evil-maid-lib
> +        message "TPM 2.0 is unsupported"
```suggestion
        message "TPM 2.0 detected. TPM 2.0 is currently unsupported"
```

2023-05-31 11:50 UTC, macpijan commented
Got it @marmarek .

For this one, I think it should not break anything - the TPM1.2 should work as before. On the TPM2.0 it would error out.

2023-06-01 22:54 UTC, marmarek approved these changes

2023-06-01 22:55 UTC, merged